/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quiz;
import java.awt.Color;
import java.sql.*;
/**
 *
 * @author Admin
 */
public class AdminCategories extends javax.swing.JFrame {
ConnectionClass cobj;
PreparedStatement pst;
ResultSet rst;long ind;
    /**
     * Creates new form AdminCategories
     */
    public AdminCategories() {
        initComponents();
        cobj=new ConnectionClass();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchjTextField1 = new javax.swing.JTextField();
        savejButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        namejTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        updatejButton2 = new javax.swing.JButton();
        searchjButton4 = new javax.swing.JButton();
        next = new javax.swing.JButton();
        errjLabel4 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("All Categories");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Categories");

        savejButton1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        savejButton1.setText("Save");
        savejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Category Name");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Search Category");

        updatejButton2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        updatejButton2.setText("Update");
        updatejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButton2ActionPerformed(evt);
            }
        });

        searchjButton4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        searchjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Quiz/Search-icon.png"))); // NOI18N
        searchjButton4.setText("Search");
        searchjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButton4ActionPerformed(evt);
            }
        });

        next.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        errjLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(savejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(searchjButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(updatejButton2)
                        .addGap(18, 18, 18)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(errjLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchjButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatejButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(errjLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButton1ActionPerformed
        // TODO add your handling code here:
        errjLabel4.setForeground(Color.red);
        if(namejTextField3.getText().equals(""))
            errjLabel4.setText("Enter Category Name");
        else
        {
            cobj.Connect();
            try{
                //errjLabel4.setText("45");
                pst=cobj.con.prepareCall("{call InsCategory(?)}");
            pst.setString(1, namejTextField3.getText());
            if(pst.execute()==false)
            {
                if(pst.getUpdateCount()>0)
                {
                    errjLabel4.setForeground(Color.green);
                    errjLabel4.setText("Saved");
                    searchjTextField1.setText("");
                     namejTextField3.setText("");
                }
                  else{
                errjLabel4.setText("Category already exists");
            }
            }
          
            }
            catch(Exception ex){
                errjLabel4.setText("error in save"+ex);
            }
            cobj.DisConnect();
        }
    }//GEN-LAST:event_savejButton1ActionPerformed

    private void searchjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButton4ActionPerformed
        // TODO add your handling code here:
        errjLabel4.setText("");
             
        errjLabel4.setForeground(Color.red);
        if(searchjTextField1.getText().equals(""))
            errjLabel4.setText("Enter something in search");
        else
        {
            cobj.Connect();
            try{
                String str=searchjTextField1.getText();
                String str2="%";
                for(int i=0;i<str.length();i++)
                    str2+=str.charAt(i)+"%";
                pst=cobj.con.prepareStatement("select * from tbCategory where name like ?");
                pst.setString(1, str2);
                rst=pst.executeQuery();
                if(rst.next())
                {
                  ind=rst.getLong(1);
                  namejTextField3.setText(rst.getString(2));
                }
              
            }
            catch(Exception ex)
            {
                errjLabel4.setText("error in search"+ex);
            }
           
        }
    }//GEN-LAST:event_searchjButton4ActionPerformed

    private void updatejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButton2ActionPerformed
        // TODO add your handling code here:
        errjLabel4.setForeground(Color.red);
        if(namejTextField3.getText().equals(""))
            errjLabel4.setText("Enter Category Name");
        else
        {
            cobj.Connect();
            try{
                pst=cobj.con.prepareCall("{call UPCategory(?,?)}");
            pst.setLong(1,ind);
            pst.setString(2,namejTextField3.getText() );
            if(pst.execute()==false)
            {
                if(pst.getUpdateCount()>0)
                {
                    errjLabel4.setForeground(Color.green);
                    errjLabel4.setText("Updated");
                  
                     namejTextField3.setText("");
                }
            }
            }
            catch(Exception ex){
                errjLabel4.setText("error in update"+ex);
            }
            
        }
    }//GEN-LAST:event_updatejButton2ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        try{
            if(rst.next())
        {
            ind =rst.getLong(1);
            namejTextField3.setText(rst.getString(2));
        }
            else
            {
                errjLabel4.setForeground(Color.blue);
                errjLabel4.setText("Search Completed");
                     
            }
        }
        catch(Exception ex)
        {
            errjLabel4.setText("error"+ex);
        }
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCategories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCategories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errjLabel4;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField namejTextField3;
    private javax.swing.JButton next;
    private javax.swing.JButton savejButton1;
    private javax.swing.JButton searchjButton4;
    private javax.swing.JTextField searchjTextField1;
    private javax.swing.JButton updatejButton2;
    // End of variables declaration//GEN-END:variables
}
