/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quiz;
import java.awt.Color;
import java.sql.*;
import javax.swing.JComboBox;

/**
 *
 * @author Admin
 */
public class AdminQuestions extends javax.swing.JFrame {
ConnectionClass cobj;
PreparedStatement pst;
ResultSet rst;
long ind, id[];int index;
    /**
     * Creates new form Questioninsert
     */
    public AdminQuestions() {
        initComponents();
        cobj=new ConnectionClass();
        id=new long[100];
        index=0;
        cobj.Connect();
        try{
        pst=cobj.con.prepareStatement("select Categoryid ,Name from tbCategory");
        rst=pst.executeQuery();
        while(rst.next())
        {
          id[index]=rst.getLong(1);
            index++;
            categoryjComboBox1.addItem(rst.getString(2));
        }
        rst.close();
    }
        catch(Exception ex){
            System.out.println("error in populating"+ex);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        categoryjComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        quesjTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        answer1jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        answer2jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        answer4jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        answer3jTextArea5 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        savejButton1 = new javax.swing.JButton();
        searchjButton2 = new javax.swing.JButton();
        updatejButton3 = new javax.swing.JButton();
        rightjLabel8 = new javax.swing.JLabel();
        errjLabel8 = new javax.swing.JLabel();
        nextjButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("All questions");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Questions");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel2.setText("Select a Category");

        quesjTextArea1.setColumns(20);
        quesjTextArea1.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        quesjTextArea1.setLineWrap(true);
        quesjTextArea1.setRows(5);
        quesjTextArea1.setWrapStyleWord(true);
        quesjTextArea1.setMinimumSize(new java.awt.Dimension(4, 10));
        jScrollPane1.setViewportView(quesjTextArea1);

        answer1jTextArea2.setColumns(20);
        answer1jTextArea2.setLineWrap(true);
        answer1jTextArea2.setRows(5);
        answer1jTextArea2.setToolTipText("");
        answer1jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(answer1jTextArea2);

        answer2jTextArea3.setColumns(20);
        answer2jTextArea3.setLineWrap(true);
        answer2jTextArea3.setRows(5);
        answer2jTextArea3.setWrapStyleWord(true);
        jScrollPane3.setViewportView(answer2jTextArea3);

        answer4jTextArea4.setColumns(20);
        answer4jTextArea4.setLineWrap(true);
        answer4jTextArea4.setRows(5);
        answer4jTextArea4.setWrapStyleWord(true);
        jScrollPane4.setViewportView(answer4jTextArea4);

        answer3jTextArea5.setColumns(20);
        answer3jTextArea5.setLineWrap(true);
        answer3jTextArea5.setRows(5);
        answer3jTextArea5.setWrapStyleWord(true);
        jScrollPane5.setViewportView(answer3jTextArea5);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("1)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("3)");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("2)");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("4)");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ques:");

        savejButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        savejButton1.setText("Save");
        savejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButton1ActionPerformed(evt);
            }
        });

        searchjButton2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        searchjButton2.setText("Search");
        searchjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButton2ActionPerformed(evt);
            }
        });

        updatejButton3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        updatejButton3.setText("Update");
        updatejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButton3ActionPerformed(evt);
            }
        });

        rightjLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rightjLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightjLabel8.setText("Right Option");

        errjLabel8.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N

        nextjButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        nextjButton1.setText("Next");
        nextjButton1.setMaximumSize(new java.awt.Dimension(77, 25));
        nextjButton1.setMinimumSize(new java.awt.Dimension(77, 25));
        nextjButton1.setPreferredSize(new java.awt.Dimension(77, 25));
        nextjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextjButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Option--", "1", "2", "3", "4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(categoryjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(errjLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(rightjLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(savejButton1)
                .addGap(33, 33, 33)
                .addComponent(searchjButton2)
                .addGap(27, 27, 27)
                .addComponent(updatejButton3)
                .addGap(18, 18, 18)
                .addComponent(nextjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightjLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(savejButton1)
                    .addComponent(searchjButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updatejButton3)
                        .addComponent(nextjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(errjLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButton1ActionPerformed
        // TODO add your handling code here:
        errjLabel8.setForeground(Color.red);
        if(quesjTextArea1.getText().equals(""))
            errjLabel8.setText("Enter Question");
        else if(answer1jTextArea2.getText().equals(""))
            errjLabel8.setText("Enter 1st Option");
        else if(answer2jTextArea3.getText().equals(""))
            errjLabel8.setText("Enter 2nd Option");
        else  if(answer3jTextArea5.getText().equals(""))
            errjLabel8.setText("Enter 3rd Option");
        else if(answer4jTextArea4.getText().equals(""))
            errjLabel8.setText("Enter 4th Option");
        else  if (jComboBox1.getSelectedIndex()==0)
        errjLabel8.setText("Choose correct answer");
        else
        {
            cobj.Connect();
            try{
                pst=cobj.con.prepareCall("{call InsQuestion (?,?,?,?,?,?,?)}");
                pst.setString(1, quesjTextArea1.getText());
                pst.setString(2, answer1jTextArea2.getText());
                pst.setString(3, answer2jTextArea3.getText());
                pst.setString(4, answer3jTextArea5.getText());
                pst.setString(5, answer4jTextArea4.getText());
                pst.setInt(6,Integer.parseInt(jComboBox1.getSelectedItem().toString()));
        
                pst.setLong(7, id[categoryjComboBox1.getSelectedIndex()]);
                if (pst.execute()==false)
               if(pst.getUpdateCount()>0)
               {
                   errjLabel8.setForeground(Color.green);
               errjLabel8.setText("Question Saved");
               quesjTextArea1.setText("");
               answer1jTextArea2.setText("");
               answer2jTextArea3.setText("");
               answer3jTextArea5.setText("");
               answer4jTextArea4.setText("");
               jComboBox1.setSelectedIndex(0);
               
               }
            }
            catch(Exception ex)
            {
                errjLabel8.setText("error in save"+ex);
           }
            cobj.DisConnect();
        }
    }//GEN-LAST:event_savejButton1ActionPerformed

    private void searchjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButton2ActionPerformed
        // TODO add your handling code here:
        try{
        pst=cobj.con.prepareStatement("select * from tbQuestion where categoryid=?");
         pst.setLong(1, id[categoryjComboBox1.getSelectedIndex()]);
         rst=pst.executeQuery();
         if(rst.next())
         {
             ind=rst.getLong(1);
             quesjTextArea1.setText(rst.getString(2));
             answer1jTextArea2.setText(rst.getString(3));
             answer2jTextArea3.setText(rst.getString(4));
             answer3jTextArea5.setText(rst.getString(5));
             answer4jTextArea4.setText(rst.getString(6));
             jComboBox1.setSelectedIndex(rst.getInt(7));
             categoryjComboBox1.setSelectedIndex(new ArraySearchClass().searchArray(id, rst.getLong(8),0));
              errjLabel8.setText((""));
         }
        // rst.close();
        }
        catch(Exception ex)
        {
            errjLabel8.setText("error in search"+ex);
        }
        
      //  cobj.DisConnect();
    }//GEN-LAST:event_searchjButton2ActionPerformed

    private void updatejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButton3ActionPerformed
        // TODO add your handling code here:
        errjLabel8.setForeground(Color.red);
        if(quesjTextArea1.getText().equals(""))
            errjLabel8.setText("Enter Question");
        else if(answer1jTextArea2.getText().equals(""))
            errjLabel8.setText("Enter 1st Option");
        else if(answer2jTextArea3.getText().equals(""))
            errjLabel8.setText("Enter 2nd Option");
        else  if(answer3jTextArea5.getText().equals(""))
            errjLabel8.setText("Enter 3rd Option");
        else if(answer4jTextArea4.getText().equals(""))
            errjLabel8.setText("Enter 4th Option");
          else  if (jComboBox1.getSelectedIndex()==0)
        errjLabel8.setText("Choose correct answer");
        
        else
        {
            cobj.Connect();
            try{
                pst=cobj.con.prepareCall("{call UPQuestion (?,?,?,?,?,?,?,?)}");
                pst.setLong(1, ind);
                pst.setString(2, quesjTextArea1.getText());
                pst.setString(3, answer1jTextArea2.getText());
                pst.setString(4, answer2jTextArea3.getText());
                pst.setString(5, answer3jTextArea5.getText());
                pst.setString(6, answer4jTextArea4.getText());
                pst.setInt(7,Integer.parseInt(jComboBox1.getSelectedItem().toString()));
                pst.setLong(8, id[categoryjComboBox1.getSelectedIndex()]);
                if (pst.execute()==false)
               if(pst.getUpdateCount()>0)
               {
               errjLabel8.setForeground(Color.green);
               errjLabel8.setText("Question Updated");
               quesjTextArea1.setText("");
               answer1jTextArea2.setText("");
               answer2jTextArea3.setText("");
               answer3jTextArea5.setText("");
               answer4jTextArea4.setText("");
               jComboBox1.setSelectedItem(0);
                            
               }   }
            catch(Exception ex)
            {
                errjLabel8.setText("error in Updation"+ex);
           }
            
        }
    }//GEN-LAST:event_updatejButton3ActionPerformed

    private void nextjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextjButton1ActionPerformed
        // TODO add your handling code here:
       try{ if(rst.next())
         {
             ind=rst.getLong(1);
             quesjTextArea1.setText(rst.getString(2));
             answer1jTextArea2.setText(rst.getString(3));
             answer2jTextArea3.setText(rst.getString(4));
             answer3jTextArea5.setText(rst.getString(5));
             answer4jTextArea4.setText(rst.getString(6));
             jComboBox1.setSelectedIndex(rst.getInt(7));
              categoryjComboBox1.setSelectedIndex(new ArraySearchClass().searchArray(id, rst.getLong(8),0));
         }
       else
       {
           errjLabel8.setForeground(Color.red);
        errjLabel8.setText("All questions are for this topic are exhausted");
       }
       
       }
       catch(Exception ex)
       {
           errjLabel8.setText("error"+ex);
       }
    }//GEN-LAST:event_nextjButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminQuestions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea answer1jTextArea2;
    private javax.swing.JTextArea answer2jTextArea3;
    private javax.swing.JTextArea answer3jTextArea5;
    private javax.swing.JTextArea answer4jTextArea4;
    private javax.swing.JComboBox<String> categoryjComboBox1;
    private javax.swing.JLabel errjLabel8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton nextjButton1;
    private javax.swing.JTextArea quesjTextArea1;
    private javax.swing.JLabel rightjLabel8;
    private javax.swing.JButton savejButton1;
    private javax.swing.JButton searchjButton2;
    private javax.swing.JButton updatejButton3;
    // End of variables declaration//GEN-END:variables
}
