/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quiz;
import java.awt.Color;
import java.sql.*;
/**
 *
 * @author Admin
 */
public class Categories extends javax.swing.JFrame {
ConnectionClass cobj;
PreparedStatement pst;
ResultSet rst;
long id[];int index;
public static long categorypass;
    /**
     * Creates new form Categories
     */
    public Categories() {
        initComponents();
         cobj=new ConnectionClass();
        index=1;
        id=new long[100];
       id[0]=0;
        cobj.Connect();
        try{
        pst=cobj.con.prepareStatement("select CategoryID ,Name from tbCategory");
        rst=pst.executeQuery();
        while(rst.next())
        {
          id[index]=rst.getLong(1);
            index++;
            categoryjComboBox1.addItem(rst.getString(2));
        }
        rst.close();
    }
        catch(Exception ex){
            errjLabel3.setText("error in populating"+ex);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        startjButton1 = new javax.swing.JButton();
        categoryjComboBox1 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        errjLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Category");
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Category");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select a category");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 105, -1, -1));

        startjButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        startjButton1.setText("Start Quiz");
        startjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startjButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(startjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 201, -1, -1));

        categoryjComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Option--" }));
        categoryjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryjComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(categoryjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 140, 28));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 108, 10));

        errjLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(errjLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 180, 28));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startjButton1ActionPerformed
        // TODO add your handling code here:
        errjLabel3.setForeground(Color.red);
        if(categoryjComboBox1.getSelectedIndex()==0)
            errjLabel3.setText("Please Select Category");
        else
        {
            errjLabel3.setText("");
            categorypass=id[categoryjComboBox1.getSelectedIndex()];
            Questions qu=new Questions();
        qu.setVisible(true);
        }
         
    }//GEN-LAST:event_startjButton1ActionPerformed

    private void categoryjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryjComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoryjComboBox1;
    private javax.swing.JLabel errjLabel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton startjButton1;
    // End of variables declaration//GEN-END:variables
}
