/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quiz;

import java.awt.Color;
import java.sql.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author Admin
 */
public class Questions extends javax.swing.JFrame {
ConnectionClass cobj;
PreparedStatement pst;
ResultSet rst; int increment;long waste,waste1;float Score;int ans;
int rightanswer,wronganswers;
    /**
     * Creates new form Questions
     */
    public Questions() {
        initComponents();increment=1;Score=0.0f;
        rightanswer=wronganswers=0;
        cobj=new ConnectionClass();
        submittestjButton3.setEnabled(false);
        nextjButton2.setEnabled(false);
        scorejLabel2.setText("Score:"+Score);
     buttonGroup1.add(jRadioButton1);
     buttonGroup1.add(jRadioButton2);
     buttonGroup1.add(jRadioButton3);
     buttonGroup1.add(jRadioButton4);
     cobj.Connect();
     try{
         pst=cobj.con.prepareStatement("select * from tbQuestion where categoryid=?");
         pst.setLong(1,new Categories().categorypass);
     rst=pst.executeQuery();
     if(rst.next())
     {
         waste=rst.getLong(1);
         quesjLabel3.setText(rst.getString(2));
         answer1jLabel4.setText(rst.getString(3));
         answer2jLabel6.setText(rst.getString(4));
         answer3jLabel7.setText(rst.getString(5));
         answer4jLabel5.setText(rst.getString(6));
         ans=rst.getInt(7);
         waste1=rst.getLong(8);
     }
     else
     {
         errjLabel4.setForeground(Color.red);
         errjLabel4.setText("No questions are available");
     }
     }
     catch(Exception ex)
     {
         errjLabel4.setText("error"+ex);
     }
     
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        incjLabel2 = new javax.swing.JLabel();
        quesjLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        submitanswerjButton1 = new javax.swing.JButton();
        errjLabel4 = new javax.swing.JLabel();
        answer1jLabel4 = new javax.swing.JLabel();
        answer4jLabel5 = new javax.swing.JLabel();
        answer2jLabel6 = new javax.swing.JLabel();
        answer3jLabel7 = new javax.swing.JLabel();
        nextjButton2 = new javax.swing.JButton();
        submittestjButton3 = new javax.swing.JButton();
        scorejLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Question");
        setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Question No.");

        incjLabel2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        incjLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incjLabel2.setText("1");

        quesjLabel3.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N

        jRadioButton1.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N

        jRadioButton3.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N

        submitanswerjButton1.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        submitanswerjButton1.setText("Submit Answer");
        submitanswerjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitanswerjButton1ActionPerformed(evt);
            }
        });

        errjLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        answer1jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        answer4jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        answer2jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        answer3jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        nextjButton2.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        nextjButton2.setText("Next");
        nextjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextjButton2ActionPerformed(evt);
            }
        });

        submittestjButton3.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        submittestjButton3.setText("Submit Test");
        submittestjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submittestjButton3ActionPerformed(evt);
            }
        });

        scorejLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitanswerjButton1)
                .addGap(39, 39, 39)
                .addComponent(nextjButton2)
                .addGap(28, 28, 28)
                .addComponent(submittestjButton3)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(answer1jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(answer2jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(quesjLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(answer3jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(errjLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(incjLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scorejLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answer4jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(incjLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(quesjLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(answer1jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(answer2jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(answer3jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answer4jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitanswerjButton1)
                            .addComponent(nextjButton2)
                            .addComponent(submittestjButton3)))
                    .addComponent(scorejLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(errjLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void submitanswerjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitanswerjButton1ActionPerformed
        // TODO add your handling code here:
        
        if(!jRadioButton1.isSelected()&&!jRadioButton2.isSelected()&&!jRadioButton3.isSelected()&&!jRadioButton4.isSelected())
        {
            errjLabel4.setText("Select one Option");
            errjLabel4.setForeground(Color.red);
        }
        else{
            errjLabel4.setText("");
            if(jRadioButton1.isSelected()&&ans==1)
            {Score++;errjLabel4.setText("Right Answer");
            rightanswer++;errjLabel4.setForeground(Color.green);}
       else if(jRadioButton2.isSelected()&&ans==2)
           {Score++;errjLabel4.setText("Right Answer");
           rightanswer++;errjLabel4.setForeground(Color.green);}
       else if(jRadioButton3.isSelected()&&ans==3)
          {Score++;errjLabel4.setText("Right Answer");
          rightanswer++;errjLabel4.setForeground(Color.green);}
       else if(jRadioButton4.isSelected()&&ans==4)
           {Score++;errjLabel4.setText("Right Answer");
           rightanswer++;errjLabel4.setForeground(Color.green);}
       else {errjLabel4.setText("Wrong Answer");wronganswers++;
       errjLabel4.setForeground(Color.red);}
       scorejLabel2.setText("Score:"+Score);
       nextjButton2.setEnabled(true);
       buttonGroup1.clearSelection();
             submitanswerjButton1.setEnabled(false);
      jRadioButton1.setEnabled(false);
      jRadioButton2.setEnabled(false);
       jRadioButton3.setEnabled(false);
        jRadioButton4.setEnabled(false);
    
      
        }
    }//GEN-LAST:event_submitanswerjButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void nextjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextjButton2ActionPerformed
        // TODO add your handling code here:
      nextjButton2.setEnabled(false);errjLabel4.setText("");
      /* if(increment==1&&!jRadioButton1.isSelected()&&!jRadioButton2.isSelected()&&!jRadioButton3.isSelected()&&!jRadioButton4.isSelected())
        {
            errjLabel4.setText("Select one Option");
            errjLabel4.setForeground(Color.red);
        }*/
      
       
          submitanswerjButton1.setEnabled(true);
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
        jRadioButton3.setEnabled(true);
        jRadioButton4.setEnabled(true); 
           System.out.print("45");  try{
        if(rst.next())
        {System.out.print("45");
            increment++;
            incjLabel2.setText(increment+"");
            waste=rst.getLong(1);
         quesjLabel3.setText(rst.getString(2));
         answer1jLabel4.setText(rst.getString(3));
         answer2jLabel6.setText(rst.getString(4));
         answer3jLabel7.setText(rst.getString(5));
         answer4jLabel5.setText(rst.getString(6));
         ans=rst.getInt(7);
         waste1=rst.getLong(8);
            
        }
        else
        {
            buttonGroup1.clearSelection();
          
      jRadioButton1.setEnabled(false);
      jRadioButton2.setEnabled(false);
       jRadioButton3.setEnabled(false);
        jRadioButton4.setEnabled(false);
            submitanswerjButton1.setEnabled(false);
            submittestjButton3.setEnabled(true);
            
        }
    }
        catch(Exception ex)
                {
                errjLabel4.setText("error"+ex);
                }
    }//GEN-LAST:event_nextjButton2ActionPerformed

    private void submittestjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submittestjButton3ActionPerformed
        // TODO add your handling code here:
        cobj.Connect();
        try{
            pst=cobj.con.prepareCall("{call InsResult(?,?,?,?,?,?,?)}");
            pst.setLong(1, new Player_Login().registeridpass);
             pst.setLong(2, new Categories().categorypass);
             DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM/dd/yyyy");
         	LocalDate localDate = LocalDate.now();
             String str=dtf.format(localDate);
            // System.out.println(str);//2016/11/16
             pst.setString(3, str);
             pst.setInt(4,increment);
             pst.setInt(5, rightanswer);
             pst.setInt(6,wronganswers);
             pst.setFloat(7,Score);
             if(pst.execute()==false)
             {
                 if(pst.getUpdateCount()>0)
                 {
                     errjLabel4.setForeground(Color.green);
                     errjLabel4.setText("Result Recorded");
                     
                     new resultpage().setVisible(true);
                 }
             }
        }
        catch(Exception ex)
        {
            //System.out.println("error"+ex);
           errjLabel4.setText("error in submit"+ex);
        }
        cobj.DisConnect();
    }//GEN-LAST:event_submittestjButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answer1jLabel4;
    private javax.swing.JLabel answer2jLabel6;
    private javax.swing.JLabel answer3jLabel7;
    private javax.swing.JLabel answer4jLabel5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel errjLabel4;
    private javax.swing.JLabel incjLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JButton nextjButton2;
    private javax.swing.JLabel quesjLabel3;
    private javax.swing.JLabel scorejLabel2;
    private javax.swing.JButton submitanswerjButton1;
    private javax.swing.JButton submittestjButton3;
    // End of variables declaration//GEN-END:variables
}
