/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java1;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class Purchase_Form extends javax.swing.JFrame {
ConnectionClass cobj;
PreparedStatement pst;
ResultSet rst;
long proid[];long venid[];
int index1,index2;
long id1,id2;
/**
     * Creates new form Purchase_Form
     */
    public Purchase_Form() {
        initComponents();
        cobj=new ConnectionClass();
        index1=index2=0;
        proid=new long[100];
        venid=new long[100];
        cobj.Connect();
        try{
        pst=cobj.con.prepareStatement("select ProductID ,Name from tbProduct");
        rst=pst.executeQuery();
        while(rst.next())
        {
          proid[index1]=rst.getLong(1);
            index1++;
            projComboBox1.addItem(rst.getString(2));
        }
        rst.close();
    }
        catch(Exception ex){
            errjLabel7.setText("error in populating"+ex);
                }
       
        try{
        pst=cobj.con.prepareStatement("select vendorID ,Name from tbVendor");
        rst=pst.executeQuery();
        while(rst.next())
        {
          venid[index2]=rst.getLong(1);
            index2++;
            vendorjComboBox2.addItem(rst.getString(2));
        }
        rst.close();
    }
        catch(Exception ex){
            errjLabel7.setText("error in populating"+ex);
                }
        cobj.DisConnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purjLabel1 = new javax.swing.JLabel();
        pronamejLabel2 = new javax.swing.JLabel();
        quantityjLabel3 = new javax.swing.JLabel();
        ratejLabel4 = new javax.swing.JLabel();
        projComboBox1 = new javax.swing.JComboBox<>();
        amountjLabel5 = new javax.swing.JLabel();
        vendorjLabel6 = new javax.swing.JLabel();
        errjLabel7 = new javax.swing.JLabel();
        purjTextField1 = new javax.swing.JTextField();
        quantityjTextField2 = new javax.swing.JTextField();
        ratejTextField3 = new javax.swing.JTextField();
        amountjTextField4 = new javax.swing.JTextField();
        vendorjComboBox2 = new javax.swing.JComboBox<>();
        savejButton1 = new javax.swing.JButton();
        searchjButton2 = new javax.swing.JButton();
        updatejButton3 = new javax.swing.JButton();
        resetjButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        purjLabel1.setText("Purchase Date");
        getContentPane().add(purjLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 39, -1, -1));

        pronamejLabel2.setText("Product Name");
        getContentPane().add(pronamejLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 77, -1, -1));

        quantityjLabel3.setText("Quantity");
        getContentPane().add(quantityjLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 115, -1, -1));

        ratejLabel4.setText("Rate");
        getContentPane().add(ratejLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 153, -1, -1));

        getContentPane().add(projComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 74, 170, -1));

        amountjLabel5.setText("Amount");
        getContentPane().add(amountjLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 185, -1, 20));

        vendorjLabel6.setText("Vendor Name");
        getContentPane().add(vendorjLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 226, -1, -1));
        getContentPane().add(errjLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 484, 35));
        getContentPane().add(purjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 36, 170, -1));
        getContentPane().add(quantityjTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 112, 170, -1));
        getContentPane().add(ratejTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 150, 170, -1));
        getContentPane().add(amountjTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 185, 170, -1));

        vendorjComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorjComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(vendorjComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 223, 171, -1));

        savejButton1.setText("Save");
        savejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(savejButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 261, -1, -1));

        searchjButton2.setText("Search");
        searchjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(searchjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 261, -1, -1));

        updatejButton3.setText("Update");
        updatejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(updatejButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 261, -1, -1));

        resetjButton4.setText("Reset");
        getContentPane().add(resetjButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 261, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButton3ActionPerformed
        // TODO add your handling code here:
        if(purjTextField1.getText().equals(""))
            errjLabel7.setText("Enter Purchase date");
          
        else if(ratejTextField3.getText().equals(""))
            errjLabel7.setText("Enter Rate");
        else if (amountjTextField4.getText().equals(""))
            errjLabel7.setText("Enter Amount");
                    else if (quantityjTextField2.getText().equals(""))
              errjLabel7.setText("Enter Quantity");
       else {
                  
        cobj.Connect();
                  try{
                  pst=cobj.con.prepareCall("{call UPPurchase(?,?,?,?,?,?,?)}");
                  pst.setLong(1,id1);
                  pst.setString(2, purjTextField1.getText());
                   pst.setLong(3, proid[projComboBox1.getSelectedIndex()]);
                   pst.setInt(4, Integer.parseInt(quantityjTextField2.getText()));
                   pst.setDouble(5, Double.parseDouble(ratejTextField3.getText()));
                   pst.setDouble(6,Double.parseDouble(amountjTextField4.getText()));
                   pst.setLong(7, venid[vendorjComboBox2.getSelectedIndex()]);
                    if(pst.execute()==false)
               if(pst.getUpdateCount()>0)
               {
                errjLabel7.setText("Record Updated");
                purjTextField1.setText("");
                quantityjTextField2.setText("");
                ratejTextField3.setText("");
                amountjTextField4.setText("");
            }
                  }
              catch(Exception ex){
            errjLabel7.setText("error in updation"+ex);
       }
        cobj.DisConnect();
                    }
    }//GEN-LAST:event_updatejButton3ActionPerformed

    private void savejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButton1ActionPerformed
        // TODO add your handling code here:
        if(purjTextField1.getText().equals(""))
            errjLabel7.setText("Enter Purchase date");
           else if (quantityjTextField2.getText().equals(""))
              errjLabel7.setText("Enter Quantity");
        else if(ratejTextField3.getText().equals(""))
            errjLabel7.setText("Enter Rate");
        else if (amountjTextField4.getText().equals(""))
            errjLabel7.setText("Enter Amount");
                   
        else
               {
                  cobj.Connect();
                  try{
                  pst=cobj.con.prepareCall("{call InsPurchase(?,?,?,?,?,?)}");
                   pst.setString(1, purjTextField1.getText());
                   pst.setLong(2, proid[projComboBox1.getSelectedIndex()]);
                   pst.setInt(3, Integer.parseInt(quantityjTextField2.getText()));
                   pst.setDouble(4, Double.parseDouble(ratejTextField3.getText()));
                   pst.setDouble(5,Double.parseDouble(amountjTextField4.getText()));
                   pst.setLong(6, venid[vendorjComboBox2.getSelectedIndex()]);
                    if(pst.execute()==false)
               if(pst.getUpdateCount()>0)
               {
                   pst=cobj.con.prepareStatement("select Purchaseid from tbPurchase where PurDate=?");
                   pst.setString(1, purjTextField1.getText());
                   rst=pst.executeQuery();
                   if(rst.next())
                   JOptionPane.showMessageDialog(this, "Record Save\n Your Purchase id is "+rst.getLong(1)); 
                errjLabel7.setText("Record Saved");
                purjTextField1.setText("");
                quantityjTextField2.setText("");
                ratejTextField3.setText("");
                amountjTextField4.setText("");
            }rst.close();
                  }
                 catch(Exception ex)
                  {
                     errjLabel7.setText("error"+ex);
                  }
                  cobj.DisConnect();
              }
    }//GEN-LAST:event_savejButton1ActionPerformed

    private void searchjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButton2ActionPerformed
        // TODO add your handling code here:
     
        cobj.Connect();
      try{
     pst=cobj.con.prepareStatement("select * from tbPurchase where product_id=?"); 
     pst.setLong(1, proid[projComboBox1.getSelectedIndex()]);
      rst=pst.executeQuery();
      while(rst.next())
      {
          id1=rst.getLong(1);
          purjTextField1.setText(rst.getString(2));
          projComboBox1.setSelectedIndex(new ArraySearchClass().searchArray(proid,rst.getLong(3)));
          quantityjTextField2.setText(rst.getString(4));
        ratejTextField3.setText(rst.getString(5));
        amountjTextField4.setText(rst.getString(6));
          vendorjComboBox2.setSelectedIndex(new ArraySearchClass().searchArray(venid, rst.getLong(7)));
      }rst.close();
      }
      catch(Exception ex)
      {
          errjLabel7.setText("error in search"+ex);
      }
     cobj.DisConnect();
    }//GEN-LAST:event_searchjButton2ActionPerformed

    private void vendorjComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorjComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendorjComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountjLabel5;
    private javax.swing.JTextField amountjTextField4;
    private javax.swing.JLabel errjLabel7;
    private javax.swing.JComboBox<String> projComboBox1;
    private javax.swing.JLabel pronamejLabel2;
    private javax.swing.JLabel purjLabel1;
    private javax.swing.JTextField purjTextField1;
    private javax.swing.JLabel quantityjLabel3;
    private javax.swing.JTextField quantityjTextField2;
    private javax.swing.JLabel ratejLabel4;
    private javax.swing.JTextField ratejTextField3;
    private javax.swing.JButton resetjButton4;
    private javax.swing.JButton savejButton1;
    private javax.swing.JButton searchjButton2;
    private javax.swing.JButton updatejButton3;
    private javax.swing.JComboBox<String> vendorjComboBox2;
    private javax.swing.JLabel vendorjLabel6;
    // End of variables declaration//GEN-END:variables
}
