/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java1;
import java.sql.*;
/**
 *
 * @author Admin
 */
public class Update_user extends javax.swing.JFrame {
ConnectionClass cobj;
PreparedStatement pst;
    /**
     * Creates new form Update_user
     */
    public Update_user() {
        super("Update User");
        cobj =new ConnectionClass();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unjLabel1 = new javax.swing.JLabel();
        opwjLabel2 = new javax.swing.JLabel();
        upjButton1 = new javax.swing.JButton();
        unjTextField1 = new javax.swing.JTextField();
        opwjTextField2 = new javax.swing.JTextField();
        npwjLabel3 = new javax.swing.JLabel();
        npwjTextField3 = new javax.swing.JTextField();
        errjLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        unjLabel1.setText("Username");

        opwjLabel2.setText("Old Password");

        upjButton1.setText("Update");
        upjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upjButton1ActionPerformed(evt);
            }
        });

        npwjLabel3.setText("New Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errjLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(136, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unjLabel1)
                            .addComponent(npwjLabel3)
                            .addComponent(opwjLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(upjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(npwjTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(opwjTextField2)
                            .addComponent(unjTextField1))
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unjLabel1)
                    .addComponent(unjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opwjLabel2)
                    .addComponent(opwjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npwjLabel3)
                    .addComponent(npwjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(upjButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(errjLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upjButton1ActionPerformed
        // TODO add your handling code here:
        if(unjTextField1.getText().equals(""))
            errjLabel4.setText("Enter Username");
      else  if(opwjTextField2.getText().equals(""))
            errjLabel4.setText("Enter OldPassword");
      else if(npwjTextField3.getText().equals(""))
            errjLabel4.setText("Enter NewPassword");
      else {
          cobj.Connect();
          try{
              pst=cobj.con.prepareStatement("update tbLogin set password=? where Username=? and password=?");
          pst.setString(1, npwjTextField3.getText());
              pst.setString(2, unjTextField1.getText());
          pst.setString(3,opwjTextField2.getText());
          if(pst.executeUpdate()>=1)
          {
              errjLabel4.setText("Update Successful");
              unjTextField1.setText("");
              opwjTextField2.setText("");
              npwjTextField3.setText("");
          }
          else errjLabel4.setText("error in update "); 
          
          }
          catch(Exception ex)
          {
              
          }
          cobj.DisConnect();
      }
    }//GEN-LAST:event_upjButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errjLabel4;
    private javax.swing.JLabel npwjLabel3;
    private javax.swing.JTextField npwjTextField3;
    private javax.swing.JLabel opwjLabel2;
    private javax.swing.JTextField opwjTextField2;
    private javax.swing.JLabel unjLabel1;
    private javax.swing.JTextField unjTextField1;
    private javax.swing.JButton upjButton1;
    // End of variables declaration//GEN-END:variables
}
